### ISSUE TITLE
Not indenting correctly HTML content of <script type="text/x-template"> tag (VueJS)

### ISSUE THREAD

**Issue by acrolink** [elixir-editors/vim-elixir#379]
When auto-indenting / beautifying an `.eex` file with `<script type="text/x-template">` tag (`VueJS`) the content of this tag does not get indented properly, I get:

```
<script type="text/x-template" id="property-row">
  <tr>
  <td>{{ property.code }}</td>
  <td>{{ property.name }}</td>
  <td>{{ property.id }}
  <div @click="greet(property)" class="pull-right">✔</div>
  </td>
  <td>{{ property.status }}</td>
  </tr>
</script>
```
Instead of expected:
```
<script type="text/x-template" id="property-row">
    <tr>
        <td>{{ property.code }}</td>
        <td>{{ property.name }}</td>
        <td>{{ property.id }}
            <div @click="greet(property)" class="pull-right">✔</div>
        </td>
        <td>{{ property.status }}</td>
    </tr>
</script>
```

**Comment by jbodah** [comment]
@acrolink Thanks for this. Does this also happen if you change the extension to `.html`? The indent/syntax rules all delegate to the HTML ones if they aren't handled by vim-elixir

**Comment by acrolink** [comment]
Yes, same happens if the extension is changed to `.html`. It is like anything inside a `<script>` tag is not considered HTML at all (yet in the case of a script tag of `type="text/x-template"`, the content is HTML)

**Comment by jbodah** [comment]
Since this has the same behavior with `.html` files then that means the indent is passing through `vim-elixir` unchanged and going to the base HTML indent code. This sounds like something that should be handled by a vue plugin (or other HTML templating library).

Going to close for now, but feel free to open again if there's something about `vim-elixir` that seems to cause an issue
