### ISSUE TITLE
iex returns `:noop` on recompile, nothing changes (expected `:ok`)

### ISSUE THREAD

**Issue by benjie** [elixir-editors/vim-elixir#412]
This issue is just to help others who have this problem in future.

What turned out to be the problem for me was that [ALE](https://github.com/w0rp/ale) was running linting which caused `mix` to compile the code, which meant that there was nothing for `iex` to `recompile` when asked to do so, so no code was reloaded resulting in the stale code still existing in memory.

Solution - make sure that `elixir` is present in your `g:ale_linters` and is set to an empty list:

```viml
" Disable linting in elixir so iex works
let g:ale_linters = {
      \  'elixir': []
      \}
```

cc @StephenGrider for interest since I tripped over this whilst following your course 👍

**Comment by benjie** [comment]
Self-closing, this is just for people looking for a fix later (since the behaviour didn't occur before installing `vim-elixir`)

**Comment by lovepocky** [comment]
`:echo g:ale_linters` already returns `{'elixir': []}`, but recompiled as well. unless disable the plugin.

any suggestion?
thanks.

ps: if i `:w` twice, the second write will not trigger compile. but i don't known how to use this action as autocmd

**Comment by IvanShpotenko** [comment]
You can also force `iex` to recompile the code by calling `recompile force: true` [https://hexdocs.pm/iex/IEx.Helpers.html#recompile/1-options](url)

**Comment by qhwa** [comment]
*Just for others who has the same issue, as it comes on the top of google results.*

@benjie 's solution didn't work for me. (Ubuntu 19.10, vim-gtk3). `recompile` in `iex` still returns `:noop`.

A solution from @mangalakader 's [article](https://mangalakader.github.io/post/elixir-shell-recompile-noop-issue/) works:

~~~vim
au FileType elixir let $MIX_ENV = 'test'
~~~

Since `iex` and `vim` use different `MIX_ENV`, the problem disappears.
