### ISSUE TITLE
Regexp engine.

### ISSUE THREAD

**Issue by NJichev** [elixir-editors/vim-elixir#419]
Heya, was wondering if anyone has tried the old regexpengine(set re=1) for syntax highlight, I tried benchmarking using `:syntime on` and then `:syntime report` but didn't get "good" benchmarks. You can check other stuff using `:help regexpengine`.

Remembered that old vim-ruby trick was setting re=1 since it worked faster for ruby syntax and since elixir has kind of a similar syntax thought that it'd be worth trying.

**Comment by jbodah** [comment]
I'm personally on nvim and haven't run into performance issues in awhile although they do crop up from time to time on certain files. With vim I've heard the best results coming from using the new regexpengine

I would expect vim-ruby performance tweaks to work well for vim-elixir because of how block semantics and comments/strings work (these two in combination seem to account for the slowdowns in all the cases I've investigated). If you're having slowdowns, the best data would be profiler logs, source files (if you can post them), and build information (plugins/vimrc, vim/nvim, versions, regexpengine settings) and preferably as clean and widdled down as possible (fresh vimrc that is still slowing down)

**Comment by NJichev** [comment]
I’m closing, just wanted you to look at it as something that may gain performance.

**Comment by jbodah** [comment]
@mhinz here's a link to one (haven't tested with HEAD in awhile but it should still be slow). https://github.com/elixir-editors/vim-elixir/issues/407#issue-294044016

The performance issue happens in `searchpair` when the skip expression is checking the syntax to try and ignore strings and comments. Optimizations to the indent (reduce the number of lookups) and optimizations to the regex (make the lookups faster) would both have a big impact

I have some branches where I'm trying a different indent strategy (only look at last few lines + some state) but it's slow going fixing the regressions

**Comment by mhinz** [comment]
Hmm, I see. It's the `synID()` which is pretty slow (as the help already mentions). But it's also the only way if the syntax group must be used.

It's just that `searchpair()` runs `s:is_string_or_comment()` very often.. hmm.
