### ISSUE TITLE
formatting with gq has indent issues with selections

### ISSUE THREAD

**Issue by kswope** [elixir-editors/vim-elixir#439]
I've not seen this problem with other formatters so it might just be a convention is not being followed.

start with this
```
defmodule Module do
def function do
IO.puts("hello")
end
end
```

Select the whole thing and type gq, everything looks good
```
defmodule Module do
  def function do
    IO.puts("hello")
  end
end
```

But if I want to just format a region by selecting only the function, which I often do because I don't like how the vim formatter handles blank lines.
```
defmodule Module do
def function do
  IO.puts("hello")
end
end
```

**Comment by jbodah** [comment]
> it might just be a convention is not being followed

This wouldn't surprise me. The indent rules are based on syntax block depth rather than being relative (although I believe the next iteration of indent will be relative)

The example you posted surprises me. Could you post the exact command you're using? Also would you mind setting `let g:elixir_indent_debug=1`, running your command, and then posting the output dumped in `:messages`? That should give me a better idea as to what lines are being called in what order
