### ISSUE TITLE
Highlight quotes as part of strings

### ISSUE THREAD

**Issue by ghost** [elixir-editors/vim-elixir#523]
vim-elixir does not highlight the quotes surrounding strings, so if I type `"foo"` then only the `foo` part will have the string color. Other syntaxes built into vim include the quotes as part of the string, so if I type `"hello world"` then the quotes will be the same color as the contents. Can vim-elixir get changed to highlight the quotes, or perhaps get a setting to enable it?

**Comment by jbodah** [comment]
I'm a little unsure of whether or not we should add this to the plugin. I usually try to look at how other languages have dealt with this and try to keep functionality similar to whatever they did. In this case I believe vim-ruby does _not_ highlight quotes (I usually defer to vim-ruby because Ruby is syntactically very similar to Elixir)

Which ones do you know of that do?

Note that you can always customize your own vim env to do this. For example you can add this to you `VIMROOT/after/ftplugin/elixir.vim`:

```
hi def link elixirStringDelimiter String
```

Ref: https://vim.fandom.com/wiki/Keep_your_vimrc_file_clean
